In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [21]:
outer_product = [[x[i] * y[j] for j in range(len(y))] for i in range(len(x))]

In [16]:
x[:,None].shape

(3, 1)

In [17]:
y[None,:].shape

(1, 3)

In [20]:
np.abs(x[:,None] - y[None,:])

array([[3, 4, 5],
       [2, 3, 4],
       [1, 2, 3]])

In [5]:
x = np.random.rand(3,3)
y = np.random.rand(3,3)

In [7]:
vec1 = x[:, None]
vec2 = y[None, :]

result = np.abs(vec2-vec1)
result

array([[[0.63010128, 0.5633438 , 0.0581071 ],
        [0.47736747, 0.33988543, 0.16356752],
        [0.10327028, 0.3096291 , 0.15765368]],

       [[0.57136512, 0.0279391 , 0.44146365],
        [0.41863132, 0.87529013, 0.33600324],
        [0.04453413, 0.2257756 , 0.34191708]],

       [[0.717707  , 0.24001128, 0.35185218],
        [0.56497319, 0.66321795, 0.45731259],
        [0.190876  , 0.01370341, 0.45139875]]])

In [8]:
data = np.loadtxt('/dtu/projects/02613_2025/data/locations/locations_100.csv', delimiter=',', skiprows=1, usecols=(1, 2))

In [50]:
p1, p2 = np.radians(data), np.radians(data)

In [41]:
D = np.empty((len(p1), len(p2)))
for i in range(len(p1)):
    for j in range(len(p2)):
        dsin2 = np.sin(0.5 * (p1[i] - p2[j])) ** 2
        cosprod = np.cos(p1[i, 0]) * np.cos(p2[j, 0])
        a = dsin2[0] + cosprod * dsin2[1]
        D[i, j] = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

D *= 6371  # Earth radius in km

In [42]:
D.shape

(99, 99)

In [40]:
p1[0]

array([0.97854793, 1.11090207])

In [54]:
p1, p2 = np.radians(data), np.radians(data)

In [55]:
# Extract latitude and longitude
lat1, lon1 = p1[:, 0], p1[:, 1]
lat2, lon2 = p2[:, 0], p2[:, 1]

# Compute the difference in longitude
dlon = lon1[:, np.newaxis] - lon2

# Haversine formula using broadcasting
dsin2_lat = np.sin(0.5 * (lat1[:, np.newaxis] - lat2)) ** 2
dsin2_lon = np.sin(0.5 * dlon) ** 2
cosprod = np.cos(lat1[:, np.newaxis]) * np.cos(lat2)
a = dsin2_lat + cosprod * dsin2_lon

# Compute the distance
D = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

# Multiply by Earth's radius to get the distance in kilometers
D *= 6371


In [34]:
p1

array([[ 9.78547933e-01,  1.11090207e+00],
       [-9.14261639e-01, -1.31103316e+00],
       [ 8.20013860e-01,  4.52912941e-01],
       [ 1.00996386e+00,  4.25278560e-01],
       [ 7.53691348e-01,  1.90619043e+00],
       [ 5.57632696e-01,  7.84525499e-01],
       [ 1.22871179e+00, -2.59216301e+00],
       [ 2.73725804e-01,  1.85732121e+00],
       [ 8.28740506e-01,  1.66969831e-01],
       [-8.34849153e-02, -6.59443568e-01],
       [ 1.19729587e+00,  5.55014702e-01],
       [ 1.07744992e+00,  1.79448936e+00],
       [ 8.22631854e-01,  1.23336599e-01],
       [ 5.59087136e-01,  1.93324303e+00],
       [ 1.02247205e+00,  2.81870674e-01],
       [ 1.05039732e+00,  4.32550766e-01],
       [ 9.82576003e-01,  1.59254802e-01],
       [ 9.11934534e-01,  7.64163324e-01],
       [ 3.72046018e-01,  1.22725735e+00],
       [ 5.43094103e-01,  4.86370903e-01],
       [ 9.09607427e-01, -1.92160751e+00],
       [ 7.94124810e-01, -1.28398055e+00],
       [ 6.28900307e-01,  2.25816516e+00],
       [-4.

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [17]:
cosprod

0.6778253814511775

In [22]:
outer_product

[[4, 5, 6], [8, 10, 12]]

In [2]:
import numpy as np

def distmat_1d(x, y):
    x = np.array(x)[:, np.newaxis]  # Reshape x to (m, 1)
    y = np.array(y)[np.newaxis, :]  # Reshape y to (1, n)
    return abs(x - y)  # Compute absolute differences

# Example usage
x = [1, 2, 3]
y = [4, 5]
distance_matrix = distmat_1d(x, y)
print(distance_matrix)

[[3 4]
 [2 3]
 [1 2]]
